export default function PostLayout({ children }: { children: React.ReactNode }) {
    return (
        <div className="prose prose-invert max-w-none
      prose-headings:tracking-tight
      prose-p:leading-relaxed
      prose-p:my-6
      prose-a:text-ice
      hover:prose-a:text-ice-strong
      prose-h2:mt-12
      prose-h2:mb-6
      prose-h3:mt-8
      prose-h3:mb-4
      prose-ul:my-6
      prose-ol:my-6
      prose-li:my-2
      prose-blockquote:my-6
      prose-blockquote:border-l-ice
      prose-blockquote:text-muted
      prose-pre:my-6
      prose-pre:bg-surface-2
      prose-pre:border
      prose-pre:border-border
      prose-h1:text-4xl
      prose-h1:font-bold
      prose-h1:text-ice-strong
      prose-h2:text-3xl
      prose-h2:font-bold
      prose-h2:text-ice
      prose-h3:text-2xl
      prose-h3:font-semibold
      prose-h3:text-foreground
      prose-h4:text-xl
      prose-h4:font-semibold
      prose-h4:text-muted
      prose-strong:text-ice-strong
      prose-code:text-ice
    ">
            {children}
        </div>
    );
} 
